### ISSUE TITLE
Small vertical lines in color dialog palette

### ISSUE THREAD

**Issue by bjarnef** [Alberplz/angular-colorpicker-directive#1]
I noticed in the color dialog palette, that there are some small vertical lines in the gradient palette. It seems to be a calculation bug?

Tested in Chrome Version 48.0.2564.116

http://alberplz.github.io/angular-colorpicker-directive/index.html

From the demo page:

![image](https://cloud.githubusercontent.com/assets/2919859/13213147/09d4a60a-d947-11e5-8287-07918f490f99.png)

![image](https://cloud.githubusercontent.com/assets/2919859/13213117/e862cc0e-d946-11e5-85e3-3fdeae0927ad.png)

Furthermore, I am not sure if this script is the same as the project here? http://angularscript.com/angular-multi-input-color-picker/ .. for that project the "demo" and "download" links seems to be broken.

Haven't tested how well the color picker works on mobile/tablet/touch devices, but you might want to use `<input type="number" pattern="[0-9]*" />` instead of `<input type="text" />` for RGBA and HSLA input fields and you could then specify `min` and `max` attributes.
http://bradfrost.com/blog/mobile/better-numerical-inputs-for-mobile-forms/

**Comment by Alberplz** [comment]
I have included a little script to generate precalculated images:
http://alberplz.github.io/angular-colorpicker-directive/slider-creator/slider-images.html
It seems a bug in Firefox 44.0.2 for Linux, it shows url base64 images with small vertical lines. I've generated precalculated images with other browser.

I changed the project name to https://github.com/Alberplz/angular-colorpicker-directive, the same project.

Added input type="number" to show numeric keyboards in mobiles

Thank you very much!!!

**Comment by Alberplz** [comment]
New version updated

**Comment by bjarnef** [comment]
Great, you can also add `pattern="[0-9]*"` to number input making iOS devices show a different/simple numeric keypad (great if you only need to enter 0-9 and separator.

Furthermore for RGB you can add `min="0"` and `max="255"` and for alpha `min="0"` and `max="1"` plus `step="0.1"` (step = 10%) ..

**Comment by bjarnef** [comment]
On mobile/tablet/touch devices you have to tap to change color in the palette (or change on number). Maybe it can be enhanced with drag/touch support for the "circle".

**Comment by Alberplz** [comment]
Numeric types was enough to show numeric keyboard in Android, added patterns to iOS.
Now input spinners and steps are configurable. I left that to the developer taste:

color-picker-show-input-spinner="true"
color-picker-spinner-rgba-steps="5;5;5;0.1"
color-picker-spinner-hsla-steps="5;5;5;0.1"

Close this issue and open a new one with dragging support

**Comment by bjarnef** [comment]
Yes, Android doesn't support pattern attribute for `<input type="text" />` .. so Android show the numeric keypad based on the `<input type="number" />` and `pattern="[0-9]*"` is for iOS to display a different/optimized keypad when you only need to enter simple numbers.

Instead of `color-picker-show-input-spinner="true"` maybe better with `color-picker-spinner-numeric="true"` ? so it is based on the behaviour of the input.

But actually I don't think it is necessary, because you can't hide the spinners with css (at least for modern browsers):
https://css-tricks.com/snippets/css/turn-off-number-input-spinners/
http://exisweb.net/css-input-number-firefox

**Comment by bjarnef** [comment]
It would also be great if you could add some spacing between the input elements like the console color picker in Chrome.

![image](https://cloud.githubusercontent.com/assets/2919859/13271144/5cc9049e-da93-11e5-966c-a8162e1dbad6.png)

**Comment by Alberplz** [comment]
All inputs are type="number" because the numeric keyboards for mobile devices, also to change values  with the cursor. 

Browsers use to show spinners on mouse over (Explorer and Edge no shows spinners),  and Firefox always. I've try to unificate this behaviour and keep numbers centered in inputs from js code.

Yes, updated styles for inputs!!! Now in Firefox inputs are squared too.
